syntax = "proto3";

package ares.messages.device_states.chiller;

import "google/protobuf/empty.proto";
import "DeviceStateLogging/LaserChiller/ChillerState.proto";
import "device/device_state_request_filter.proto";
import "DeviceStateLogging/DevicesResponse.proto";

service ChillerStateLogging {
	rpc GetStates(datamodel.device.DeviceStateRequestFilter) returns (ChillerStateResponse);
	rpc DeleteStates(datamodel.device.DeviceStateRequestFilter) returns (google.protobuf.Empty);
	rpc GetAvailableDevices(google.protobuf.Empty) returns (DevicesResponse);
}

message ChillerStateResponse {
	map<string, StateCollection> state_map = 1;
}

message StateCollection {
	repeated ChillerState state_logs = 1;
}