syntax = "proto3";

package ares.messages.device_states.chiller;

import "google/protobuf/empty.proto";
import "DeviceStateLogging/LaserChiller/ChillerState.proto";
import "DeviceState/StateRequestFilter.proto";
import "DeviceStateLogging/DevicesResponse.proto";

service ChillerStateLogging {
	rpc GetStates(device_state.StateRequestFilter) returns (ChillerStateResponse);
	rpc DeleteStates(device_state.StateRequestFilter) returns (google.protobuf.Empty);
	rpc GetAvailableDevices(google.protobuf.Empty) returns (DevicesResponse);
}

message ChillerStateResponse {
	map<string, StateCollection> state_map = 1;
}

message StateCollection {
	repeated ChillerState state_logs = 1;
}