syntax = "proto3";

package FlirCM3.services;

import "google/protobuf/empty.proto";
import "FlirCM3Config.proto";

service FlirCM3CameraRpc {
	rpc CaptureImage(CaptureImageRequest) returns (CaptureImageResponse);
	rpc GetImage(GetImageRequest) returns (GetImageResponse);
	rpc GetDisplayImage(GetDisplayImageRequest) returns (GetDisplayImageResponse);
	rpc GetLatestImagePath(google.protobuf.Empty) returns (GetImagePathResponse);
	rpc SetExposureTime(SetExposureTimeRequest) returns (google.protobuf.Empty);

	rpc AddCM3Camera(config.FlirCM3Config) returns (google.protobuf.Empty);
	rpc RemoveCM3Camera(RemoveCameraRequest) returns (google.protobuf.Empty);
	rpc GetAllCM3Cameras(google.protobuf.Empty) returns (GetAllCamerasResponse);
	rpc UpdateCM3Camera(UpdateCameraRequest) returns (google.protobuf.Empty);
}

message UpdateCameraRequest {
	string camera_id = 1;
	config.FlirCM3Config config = 2;
}

message CaptureImageRequest {
	string camera_id = 1;
	string save_path = 2;
}

message CaptureImageResponse {
	bytes image_data = 1;
}

message GetImageRequest {
	string camera_id = 1;
}

message GetImageResponse {
	bytes image_data = 1;
}

message GetDisplayImageRequest {
	string camera_id = 1;
}

message GetDisplayImageResponse {
	bytes display_image_data = 1;
}

message GetImagePathResponse {
	string image_path = 1;
}

message SetExposureTimeRequest {
	string camera_id = 1;
	double exposure_time = 2;
}

message GetAllCamerasResponse {
	repeated CameraDescription cameras = 1;
}

message CameraDescription {
	string id = 1;
	string name = 2;
}

message RemoveCameraRequest {
	string device_id = 1;
}