<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Authentication.proto" />
    <None Remove="DeviceStateLogging\DevicesResponse.proto" />
    <None Remove="DeviceStateLogging\LaserChiller\ChillerState.proto" />
    <None Remove="DeviceStateLogging\LaserChiller\ChillerStateLogging.proto" />
    <None Remove="DeviceStateLogging\MfcStateLogging.proto" />
    <None Remove="DeviceStateLogging\SyringePump\SyringePumpState.proto" />
    <None Remove="DeviceStateLogging\SyringePump\SyringePumpStateLogging.proto" />
    <None Remove="DeviceStateLogging\Tc0304\Tc0304State.proto" />
    <None Remove="DeviceStateLogging\Tc0304\Tc0304StateLogging.proto" />
    <None Remove="DeviceStateLogging\TicStepperController\TicStepperControllerState.proto" />
    <None Remove="DeviceStateLogging\TicStepperController\TicStepperControllerStateLogging.proto" />
    <None Remove="DeviceStateLogging\TubeFurnace\TubeFurnaceStateEntity.proto" />
    <None Remove="DeviceStateLogging\TubeFurnace\TubeFurnaceStateLogging.proto" />
    <None Remove="MfcState.proto" />
		<None Remove="DeviceStateLogging\RestDevice\RestDeviceStateEntity.proto" />
		<None Remove="DeviceStateLogging\RestDevice\RestDeviceStateLogging" />
    <None Remove="SerialConnectivity.proto" />
    <None Remove="UserManagement.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ARES.Datamodel" Version="0.17.1" GeneratePathProperty="True" />
    <PackageReference Include="Google.Protobuf" Version="3.33.3" />
    <PackageReference Include="Grpc" Version="2.46.6" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

	<PropertyGroup>
		<DataModelProtoPath>$(PkgARES_Datamodel)\Proto\datamodel\</DataModelProtoPath>
	</PropertyGroup>

	<ItemGroup>
    <Protobuf Include="DeviceStateLogging\LaserChiller\ChillerState.proto" GrpcServices="None" />
    <Protobuf Include="DeviceStateLogging\LaserChiller\ChillerStateLogging.proto" AdditionalImportDirs="$(DataModelProtoPath)" />
    <Protobuf Include="DeviceStateLogging\Mfc\MfcStateLogging.proto" GrpcServices="Both" AdditionalImportDirs="$(DataModelProtoPath)" />
    <Protobuf Include="DeviceStateLogging\DevicesResponse.proto" GrpcServices="None" />
    <Protobuf Include="DeviceStateLogging\RestSerialDevice\RestSerialDeviceStateEntity.proto">
      <GrpcServices>None</GrpcServices>
      <Access>Public</Access>
      <ProtoCompile>True</ProtoCompile>
      <CompileOutputs>True</CompileOutputs>
      <OutputDir>obj\Debug/net6.0/</OutputDir>
      <Generator>MSBuild:Compile</Generator>
    </Protobuf>
    <Protobuf Include="DeviceStateLogging\RestSerialDevice\RestSerialDeviceStateLogging.proto" AdditionalImportDirs="$(DataModelProtoPath)">
      <GrpcServices>Both</GrpcServices>
      <Access>Public</Access>
      <ProtoCompile>True</ProtoCompile>
      <CompileOutputs>True</CompileOutputs>
      <OutputDir>obj\Debug/net6.0/</OutputDir>
      <Generator>MSBuild:Compile</Generator>
    </Protobuf>
    <Protobuf Include="DeviceStateLogging\Mfc\MfcState.proto" GrpcServices="None" />
    <Protobuf Include="DeviceStateLogging\SyringePump\SyringePumpState.proto">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Protobuf>
    <Protobuf Include="DeviceStateLogging\SyringePump\SyringePumpStateLogging.proto" GrpcServices="Both" AdditionalImportDirs="$(DataModelProtoPath)" />

    <Protobuf Include="DeviceStateLogging\Tc0304\Tc0304State.proto" GrpcServices="None" />
    <Protobuf Include="DeviceStateLogging\Tc0304\Tc0304StateLogging.proto" AdditionalImportDirs="$(DataModelProtoPath)" />

    <Protobuf Include="DeviceStateLogging\TicStepperController\TicStepperControllerStateLogging.proto" GrpcServices="Both" AdditionalImportDirs="$(DataModelProtoPath)" />
    <Protobuf Include="DeviceStateLogging\TicStepperController\TicStepperControllerState.proto" GrpcServices="None" />

		<Protobuf Include="DeviceStateLogging\RestDevice\RestDeviceStateEntity.proto" GrpcServices="None" />
		<Protobuf Include="DeviceStateLogging\RestDevice\RestDeviceStateLogging.proto" AdditionalImportDirs="$(DataModelProtoPath)" />

		<Protobuf Include="DeviceStateLogging\TubeFurnace\TubeFurnaceStateEntity.proto" GrpcServices="None" />
    <Protobuf Include="DeviceStateLogging\TubeFurnace\TubeFurnaceStateLogging.proto" AdditionalImportDirs="$(DataModelProtoPath)" />
    <Protobuf Include="SerialConnectivity.proto" />
    <Protobuf Include="UserManagement.proto" />
    <Protobuf Include="Authentication.proto" />
  </ItemGroup>

</Project>
