<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Proto\StepMode.proto" />
    <None Remove="Proto\StepperControllerConfig.proto" />
    <None Remove="Proto\StepperControllerRpc.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ares.Tools" Version="2025.8.4.112732" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.Device.Serial\AresSerial\Ares.Device.Serial.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Proto\StepperControllerRpc.proto">
      <ProtoRoot>Proto</ProtoRoot>
    </Protobuf>
    <Protobuf Include="Proto\StepMode.proto" GrpcServices="None">
      <ProtoRoot>Proto</ProtoRoot>
    </Protobuf>
    <Protobuf Include="Proto\StepperControllerConfig.proto" GrpcServices="None">
      <ProtoRoot>Proto</ProtoRoot>
    </Protobuf>
  </ItemGroup>

</Project>
