syntax = "proto3";

package HerkulexDRS.services;

import "google/protobuf/empty.proto";
import "ServoConfig.proto";
import "DataModel.proto";

service HerkulexDRSRpc {
  rpc PistonUp(DeviceRequest) returns (google.protobuf.Empty);
  rpc PistonDown(DeviceRequest) returns (google.protobuf.Empty);
  rpc ResetServo(DeviceRequest) returns (google.protobuf.Empty);
  rpc GetPosition(DeviceRequest) returns (GetPositionResponse);

  rpc AddServo(config.ServoConfig) returns (google.protobuf.Empty);
  rpc RemoveServo(HerkulexRequest) returns (google.protobuf.Empty);
  rpc GetAllServos(google.protobuf.Empty) returns (GetAllServosResponse);
  rpc UpdateServo(config.ServoConfig) returns (google.protobuf.Empty);
}

message DeviceRequest {
  string device_id = 1;
}

message HerkulexRequest {
  string herkulex_id = 1;
}

message ConnectRequest {
  string device_id = 1;
  string port_id = 2;
}

message ConnectResponse {
  bool connected = 1;
}

message GetAllServosResponse {
  repeated DeviceDescription devices = 1;
}

message DeviceDescription {
  string id = 1;
  string name = 2;
}

message GetPositionResponse {
  string response = 1;
}

message DataResponse {
  HerkulexDRS.data_model.Data data = 1;
}
