syntax = "proto3";

package ares.alicat.mfc.messaging;

import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "MfcConfig.proto";

service MfcRpc {
	rpc Connect(ConnectRequest) returns (ConnectResponse);
	rpc Disconnect(DeviceRequest) returns (google.protobuf.Empty);

	// rpc GetLiveData(DeviceRequest) returns (google.protobuf.Empty);
	// rpc StartLiveDataStream(StartLiveDataStreamRequest) returns (google.protobuf.Empty);
	// rpc QueryManufacturerInfo(DeviceRequest) returns (google.protobuf.Empty);
	rpc ChangeHardwareUnitId(ChangeUnitIdRequest) returns (google.protobuf.Empty);
	rpc TareAbsolutePressureWithBarometer(DeviceRequest) returns (google.protobuf.Empty);
	rpc TareFlow(DeviceRequest) returns (google.protobuf.Empty);
	rpc HoldValvesAtCurrentPosition(DeviceRequest) returns (google.protobuf.Empty);
	rpc HoldValvesClosed(DeviceRequest) returns (google.protobuf.Empty);
	rpc CancelValveHold(DeviceRequest) returns (google.protobuf.Empty);
	// rpc QueryGasListInfo(DeviceRequest) returns (google.protobuf.Empty);
	rpc NewComposerMix(ComposerMix) returns (google.protobuf.Empty);
	rpc DeleteComposerMix(DeleteComposerMixRequest) returns (google.protobuf.Empty);
	rpc SetSetpoint(SetSetpointRequest) returns (google.protobuf.Empty);
	rpc ChooseDifferentGas(ChooseDifferentGasRequest) returns (google.protobuf.Empty);
	rpc GetAssumedUnitId(DeviceRequest) returns (google.protobuf.Empty);
	rpc SetAssumedUnitId(SetAssumedUnitIdRequest) returns (google.protobuf.Empty);
	// rpc DisoverUnitId(DeviceRequest) returns (google.protobuf.Empty);
	rpc GetState(DeviceRequest) returns (StateResponse);
	rpc GetStateUpdate(DeviceRequest) returns (StateResponse);

	rpc GetAllMfcs(google.protobuf.Empty) returns (GetAllMfcsResponse);
	rpc GetAvailableIds(GetAvailableIdsRequest) returns (GetAvailableIdsResponse);
	rpc UpdateMfc(MfcUpdateRequest) returns (google.protobuf.Empty);
	rpc RemoveMfc(MfcRemoveRequest) returns (google.protobuf.Empty);
	rpc AddMfc(config.MfcConfig) returns (google.protobuf.Empty);
	rpc StartDataCapture(DeviceRequest) returns (google.protobuf.Empty);
}

message MfcUpdateRequest {
	string id = 1;
	config.MfcConfig config = 2;
}

message MfcRemoveRequest {
	string mfc_id = 1;
}

message ConnectRequest {
  string device_id = 1; // id of the mass flow controller
  string port_name = 2; // name of the port
}

message GetAvailableIdsRequest {
	string port_name = 1; // name of the port for which to find the available ids
	bool simulated = 2; // whether or not the given port is for a simulated connection
}

message GetAvailableIdsResponse {
	repeated string ids = 1;
}

message ConnectResponse {
  bool connected = 1; // whether or not the device successfully connected
}

message DeviceRequest {
  string device_id = 1;
}

message MfcDeviceDescription {
	string name = 1;
	string id = 2;
}

message GetAllMfcsResponse {
	repeated MfcDeviceDescription mfcs = 1;
}

message SaveResult {
	bool success = 1;
	string error = 2;
}


message StartLiveDataStreamRequest {
	DeviceRequest device_request = 1;
	google.protobuf.Duration interval = 2;
}

message DeleteComposerMixRequest {
	DeviceRequest device_request = 1; // Information required for requesting a device
	int32 mix_number = 2; // Numeric ID of the targeted COMPOSER mix to delete from the device's memory
}

message ComposerMixEntry {
	DeviceRequest device_request = 1; // Information required for requesting a device
	double percentage = 2; // Percentage of composition pertaining to the associated gas
	int32 gas_number = 3; // Numeric ID of the targeted gas
}

message ComposerMix {
	DeviceRequest device_request = 1; // Information required for requesting a device
	string name = 2; // Name of the composition
	int32 number = 3; // Numeric ID of the composition
	repeated ComposerMixEntry entries = 4; // Collection of gasses and their percentages of the overall composition
}

message ChangeUnitIdRequest {
	DeviceRequest device_request = 1; // Information required for requesting a device
	string id = 2; // Letter ID to switch the device to
}
message GetAssumedUnitIdResponse {
	string id = 1; // Letter ID assumedly assigned to the hardware according to service
}
message SetAssumedUnitIdRequest {
	DeviceRequest device_request = 1; // Information required for requesting a device
	string id = 2; // Letter ID assumedly assigned to the hardware according to service
}
message ChooseDifferentGasRequest {
	DeviceRequest device_request = 1; // Information required for requesting a device
	int32 gas_number = 2; // Numeric ID of the target gas to switch to
}

message ManufacturerInfo {
	string id = 1;
	string title = 2;
	string phone_number = 3;
	string fax = 4;
	string model_number = 5;
	string serial_number = 6;
	google.protobuf.Timestamp manufacture_date = 7;
	google.protobuf.Timestamp calibration_date = 8;
	string calibrated_by = 9;
	string software_revision = 10;
}

message GetLiveDataStreamRequest {
	DeviceRequest device_request = 1; // Information required for requesting a device
}

message SetSetpointRequest {
	DeviceRequest device_request = 1; // Information required for requesting a device
	double setpoint = 2; // the targeted mass flow of the controller in TODO units
}

message MfcLiveDataResponse {
	string id = 1; // Assigned letter ID of the mass flow controller
	UnitValue absolute_pressure = 2; // Absolute pressure
  UnitValue temperature = 3; // Temperature
  UnitValue volumetric_flow = 4; // Volumetric flow
  UnitValue mass_flow = 5; // Mass flow
  UnitValue setpoint = 6; // Targeted mass flow
	string gas = 7; // Gas abbreviation (ex: "N2")
	repeated Status status_codes = 8; // status codes of the mfc
}

message UnitValue {
	string unit = 1;
	double value = 2;
}

message GasInfoEntry {
	uint32 index = 1; // index of the gas that MFC understands
	string name = 2; // the name of the gas
}

message DataFrameFormatEntry {
	string id = 1;
  int32 line_number = 2;
	string name = 3;
	string type = 4;
	string minimum_value = 5;
	string maximum_value = 6;
	string units = 7;
	string width = 8;
	string notes = 9;
}

message ManufacturerInfoEntry
{
	string id = 1;
	int32 entry_number = 2;
	string data = 3;
	ManufacturerInfoEntryType entry_type = 4;
}

enum ManufacturerInfoEntryType
{
	INVALID = 0;
	TITLE = 1;
  PHONE_NUMBER = 2;
  FAX = 3;
  MODEL_NUMBER = 4;
  SERIAL_NUMBER = 5;
  MANUFACTURE_DATE = 6;
  CALIBRATION_DATE = 7;
  CALIBRATED_BY = 8;
  SOFTWARE_REVISION = 9;
}

enum Status {
	NA = 0;
	ADC = 1;
	LCK = 2;
	OVR = 3;
	POV = 4;
	TOV = 5;
	VOV = 6;
	MOV = 7;
	HLD = 8;
	EXH = 9;
	TMF = 10;
	OPL = 11;
}

message StateResponse {
	string assumed_id = 1;
	repeated ManufacturerInfoEntry manufacturer_info_entries = 2;
	repeated GasInfoEntry available_gas_infos = 3;
	repeated DataFrameFormatEntry data_format_entries = 4;
	MfcLiveDataResponse data = 5;
	bool has_valve = 6;
}

