syntax = "proto3";

package ares.alicat.mfc.config;

message MfcConfig {
  string name = 1; // name of the mass flow controller
  string port_name = 2; // the port name for the mfc to connect to
  string id = 3; // the id of the mass flow controller
  bool simulated = 4; // indicated whether or not the mfc is simulated
  bool has_valve = 5; // whether or not the mfc supports closing/holding valve
  MfcType mfc_type = 6; // the type of the mfc
}

enum MfcType {
  NONE = 0;
  NORMAL = 1;
  BASIS2 = 2;
}