syntax = "proto3";

option csharp_namespace = "BoraasPlanner";

import "templates/parameter_metadata.proto";
import "analyzing/analysis.proto";

package BoraasPlanner;

service BoraasPlannerGrpc {
  rpc Plan (PlanRequest) returns (PlanResultResponse);
}

message PlanResultResponse {
  repeated PlanResult plan_results = 1;
}

message PlanResult {
  ares.datamodel.templates.ParameterMetadata metadata = 1;
  string value = 2;
}

message PlanRequest {
  repeated ares.datamodel.templates.ParameterMetadata metadata = 1;
  repeated ares.datamodel.analyzing.Analysis analyses = 2;
}
