syntax = "proto3";

package tube_furnace.messaging;

import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

import "TubeFurnaceConfig.proto";


service TubeFurnaceRpc {
  rpc AddTubeFurnace(config.TubeFurnaceConfig) returns (google.protobuf.Empty);
  rpc UpdateTubeFurnace(config.TubeFurnaceConfig) returns (google.protobuf.Empty);
  rpc RemoveTubeFurnace(TubeFurnaceRequest) returns (google.protobuf.Empty);

  rpc GetState(TubeFurnaceRequest) returns (TubeFurnaceState);
  rpc GetAllTubeFurnaces(google.protobuf.Empty) returns (GetAllTubeFurnacesResponse);

  rpc GetCurrentTemperature(TubeFurnaceRequest) returns (google.protobuf.Empty);
  rpc GetSetpoint(TubeFurnaceRequest) returns (google.protobuf.Empty);
  rpc SetSetpoint(SetSetpointRequest) returns (google.protobuf.Empty);
}

message SetSetpointRequest {
  TubeFurnaceRequest device_request = 1;
  double degrees_celsius = 2;
}

message GetAllTubeFurnacesResponse {
  repeated TubeFurnaceDeviceDescription tube_furnaces = 1;
}

message TubeFurnaceRequest {
  string tube_furnace_name = 1;
}

message TubeFurnaceState {
  string name = 1; // name of the tube furnace
  double setpoint = 2; // Currently targeted temperature of the tube furnace
  double target_setpoint = 3; // User targeted temperature of the tube furnace
  double current_temperature = 4; // Current temperature of the tube furnace
  int32 assumed_address = 5; // Address used for sending software commands
}

message TubeFurnaceDeviceDescription {
	string name = 1;
	int32 assumed_address = 2;
}