// <auto-generated />
using System;
using ARESCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ARESCore.Migrations
{
    [DbContext(typeof(ARESDbContext))]
    partial class ARESDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ares.Messages.DeviceStates.Mfc.MfcState", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<double?>("AbsolutePressure")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<double?>("MassFlow")
                        .HasColumnType("float");

                    b.Property<double?>("Setpoint")
                        .HasColumnType("float");

                    b.Property<string>("StatusCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double?>("VolumetricFlow")
                        .HasColumnType("float");

                    b.HasKey("UniqueId");

                    b.ToTable("MfcStates", (string)null);
                });

            modelBuilder.Entity("Ares.Messages.DeviceStates.SyringePump.SyringePumpState", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DispensedVolume")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("RateUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("VolumeUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("WithdrawnVolume")
                        .HasColumnType("float");

                    b.HasKey("UniqueId");

                    b.ToTable("SyringePumpStates", (string)null);
                });

            modelBuilder.Entity("Ares.Messages.DeviceStates.Tc0304.Tc0304State", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<double?>("Probe1Temperature")
                        .HasColumnType("float");

                    b.Property<double?>("Probe2Temperature")
                        .HasColumnType("float");

                    b.Property<double?>("Probe3Temperature")
                        .HasColumnType("float");

                    b.Property<double?>("Probe4Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("UniqueId");

                    b.ToTable("Tc0304States", (string)null);
                });

            modelBuilder.Entity("Ares.Messages.DeviceStates.TicStepperController.TicStepperControllerState", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("CurrentPosition")
                        .HasColumnType("int");

                    b.Property<long>("CustomStepSize")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<long>("MaxAcceleration")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxDeceleration")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxSpeed")
                        .HasColumnType("bigint");

                    b.Property<long>("StartingSpeed")
                        .HasColumnType("bigint");

                    b.Property<string>("StatusMessages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StepMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetPosition")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("UniqueId");

                    b.ToTable("TicStepperControllerStates", (string)null);
                });

            modelBuilder.Entity("Ares.Messages.DeviceStates.TubeFurnace.TubeFurnaceStateEntity", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("UniqueId");

                    b.ToTable("TubeFurnaceStateEntities", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.Analysis", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CompletedExperimentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<float>("Result")
                        .HasColumnType("real");

                    b.HasKey("UniqueId");

                    b.HasIndex("CompletedExperimentId")
                        .IsUnique()
                        .HasFilter("[CompletedExperimentId] IS NOT NULL");

                    b.ToTable("Analyses", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.AnalyzerInfo", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AnalysisId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ExperimentTemplateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("AnalysisId")
                        .IsUnique()
                        .HasFilter("[AnalysisId] IS NOT NULL");

                    b.HasIndex("ExperimentTemplateId")
                        .IsUnique()
                        .HasFilter("[ExperimentTemplateId] IS NOT NULL");

                    b.ToTable("Analyzers", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.CampaignExecutionStatus", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CampaignId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("UniqueId");

                    b.ToTable("CampaignExecutionStatuses", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.CampaignResult", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CampaignId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("UniqueId");

                    b.ToTable("CampaignResults", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.CampaignTemplate", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniqueId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("CampaignTemplates", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.CommandExecutionStatus", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CommandId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StepExecutionStatusUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniqueId");

                    b.HasIndex("StepExecutionStatusUniqueId");

                    b.ToTable("CommandExecutionStatuses", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.CommandMetadata", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CommandTemplateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("CommandTemplateId")
                        .IsUnique();

                    b.ToTable("CommandMetadata");
                });

            modelBuilder.Entity("Ares.Messaging.CommandResult", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CommandId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("StepResultUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniqueId");

                    b.HasIndex("CommandId");

                    b.HasIndex("StepResultUniqueId");

                    b.ToTable("CommandResults", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.CommandTemplate", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("StepTemplateUniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniqueId");

                    b.HasIndex("StepTemplateUniqueId");

                    b.ToTable("CommandTemplates", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.CompletedExperiment", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ExperimentResultId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentResultId")
                        .IsUnique()
                        .HasFilter("[ExperimentResultId] IS NOT NULL");

                    b.ToTable("CompletedExperiments", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.Device.DeviceConfig", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("UniqueId");

                    b.ToTable("DeviceConfigs", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.DeviceCommandResult", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CommandResultId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("UniqueId");

                    b.HasIndex("CommandResultId")
                        .IsUnique()
                        .HasFilter("[CommandResultId] IS NOT NULL");

                    b.ToTable("DeviceCommandResults", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.ExecutionInfo", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CampaignResultId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommandResultId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ExperimentResultId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("StepResultId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("TimeFinished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeStarted")
                        .HasColumnType("datetime2");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignResultId")
                        .IsUnique()
                        .HasFilter("[CampaignResultId] IS NOT NULL");

                    b.HasIndex("CommandResultId")
                        .IsUnique()
                        .HasFilter("[CommandResultId] IS NOT NULL");

                    b.HasIndex("ExperimentResultId")
                        .IsUnique()
                        .HasFilter("[ExperimentResultId] IS NOT NULL");

                    b.HasIndex("StepResultId")
                        .IsUnique()
                        .HasFilter("[StepResultId] IS NOT NULL");

                    b.ToTable("ExecutionInfos", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.ExperimentExecutionStatus", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CampaignExecutionStatusUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ExperimentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignExecutionStatusUniqueId");

                    b.ToTable("ExperimentExecutionStatuses", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.ExperimentResult", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CampaignResultUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ExperimentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignResultUniqueId");

                    b.ToTable("ExperimentResults", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.ExperimentTemplate", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CampaignTemplateUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompletedExperimentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputCommandId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignTemplateUniqueId");

                    b.HasIndex("CompletedExperimentId")
                        .IsUnique()
                        .HasFilter("[CompletedExperimentId] IS NOT NULL");

                    b.ToTable("ExperimentTemplates", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.Limits", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<float>("Maximum")
                        .HasColumnType("real");

                    b.Property<float>("Minimum")
                        .HasColumnType("real");

                    b.Property<string>("ParameterMetadataUniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniqueId");

                    b.HasIndex("ParameterMetadataUniqueId");

                    b.ToTable("Limits");
                });

            modelBuilder.Entity("Ares.Messaging.OutputMetadata", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("UniqueId");

                    b.ToTable("OutputMetadata");
                });

            modelBuilder.Entity("Ares.Messaging.Parameter", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CommandTemplateUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Planned")
                        .HasColumnType("bit");

                    b.Property<string>("PlannerResponseUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlanningMetadataUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniqueId");

                    b.HasIndex("CommandTemplateUniqueId");

                    b.HasIndex("PlannerResponseUniqueId");

                    b.HasIndex("PlanningMetadataUniqueId");

                    b.ToTable("Parameters", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.ParameterMetadata", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CampaignTemplateUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommandMetadataUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlannerRequestUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignTemplateUniqueId");

                    b.HasIndex("CommandMetadataUniqueId");

                    b.HasIndex("ParameterId")
                        .IsUnique()
                        .HasFilter("[ParameterId] IS NOT NULL");

                    b.HasIndex("PlannerRequestUniqueId");

                    b.ToTable("ParameterMetadata");
                });

            modelBuilder.Entity("Ares.Messaging.ParameterValue", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ParameterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("UniqueId");

                    b.HasIndex("ParameterId")
                        .IsUnique()
                        .HasFilter("[ParameterId] IS NOT NULL");

                    b.ToTable("ParameterValues", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.PlannerAllocation", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CampaignTemplateUniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ParameterUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignTemplateUniqueId");

                    b.HasIndex("ParameterUniqueId");

                    b.ToTable("PlannerAllocations", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.PlannerInfo", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlannerAllocationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("PlannerAllocationId")
                        .IsUnique()
                        .HasFilter("[PlannerAllocationId] IS NOT NULL");

                    b.ToTable("Planners", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.PlannerRequest", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("UniqueId");

                    b.ToTable("PlannerRequests", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.PlannerResponse", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("UniqueId");

                    b.ToTable("PlannerResponses", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.PlannerTransaction", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CompletedExperimentUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("PlannerInfoUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RequestUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ResponseUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniqueId");

                    b.HasIndex("CompletedExperimentUniqueId");

                    b.HasIndex("PlannerInfoUniqueId");

                    b.HasIndex("RequestUniqueId");

                    b.HasIndex("ResponseUniqueId");

                    b.ToTable("PlannerTransactions", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.Project", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.StepExecutionStatus", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ExperimentExecutionStatusUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("StepId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentExecutionStatusUniqueId");

                    b.ToTable("StepExecutionStatuses", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.StepResult", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ExperimentResultUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("StepId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentResultUniqueId");

                    b.HasIndex("StepId");

                    b.ToTable("StepResults", (string)null);
                });

            modelBuilder.Entity("Ares.Messaging.StepTemplate", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ExperimentTemplateUniqueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsParallel")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentTemplateUniqueId");

                    b.ToTable("StepTemplates", (string)null);
                });

            modelBuilder.Entity("Google.Protobuf.WellKnownTypes.Any", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CompletedExperimentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DeviceCommandResultId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeviceConfigId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("TypeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Value")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("CompletedExperimentId")
                        .IsUnique()
                        .HasFilter("[CompletedExperimentId] IS NOT NULL");

                    b.HasIndex("DeviceCommandResultId")
                        .IsUnique()
                        .HasFilter("[DeviceCommandResultId] IS NOT NULL");

                    b.HasIndex("DeviceConfigId")
                        .IsUnique()
                        .HasFilter("[DeviceConfigId] IS NOT NULL");

                    b.ToTable("Any");
                });

            modelBuilder.Entity("Ares.Messaging.Analysis", b =>
                {
                    b.HasOne("Ares.Messaging.CompletedExperiment", "CompletedExperiment")
                        .WithOne()
                        .HasForeignKey("Ares.Messaging.Analysis", "CompletedExperimentId");

                    b.Navigation("CompletedExperiment");
                });

            modelBuilder.Entity("Ares.Messaging.AnalyzerInfo", b =>
                {
                    b.HasOne("Ares.Messaging.Analysis", null)
                        .WithOne("Analyzer")
                        .HasForeignKey("Ares.Messaging.AnalyzerInfo", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ares.Messaging.ExperimentTemplate", null)
                        .WithOne("Analyzer")
                        .HasForeignKey("Ares.Messaging.AnalyzerInfo", "ExperimentTemplateId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Messaging.CommandExecutionStatus", b =>
                {
                    b.HasOne("Ares.Messaging.StepExecutionStatus", null)
                        .WithMany("CommandExecutionStatuses")
                        .HasForeignKey("StepExecutionStatusUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Messaging.CommandMetadata", b =>
                {
                    b.HasOne("Ares.Messaging.CommandTemplate", null)
                        .WithOne("Metadata")
                        .HasForeignKey("Ares.Messaging.CommandMetadata", "CommandTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Messaging.CommandResult", b =>
                {
                    b.HasOne("Ares.Messaging.CommandTemplate", null)
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Messaging.StepResult", null)
                        .WithMany("CommandResults")
                        .HasForeignKey("StepResultUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Messaging.CommandTemplate", b =>
                {
                    b.HasOne("Ares.Messaging.StepTemplate", null)
                        .WithMany("CommandTemplates")
                        .HasForeignKey("StepTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Messaging.CompletedExperiment", b =>
                {
                    b.HasOne("Ares.Messaging.ExperimentResult", null)
                        .WithOne("CompletedExperiment")
                        .HasForeignKey("Ares.Messaging.CompletedExperiment", "ExperimentResultId");
                });

            modelBuilder.Entity("Ares.Messaging.DeviceCommandResult", b =>
                {
                    b.HasOne("Ares.Messaging.CommandResult", null)
                        .WithOne("Result")
                        .HasForeignKey("Ares.Messaging.DeviceCommandResult", "CommandResultId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Messaging.ExecutionInfo", b =>
                {
                    b.HasOne("Ares.Messaging.CampaignResult", null)
                        .WithOne("ExecutionInfo")
                        .HasForeignKey("Ares.Messaging.ExecutionInfo", "CampaignResultId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Messaging.CommandResult", null)
                        .WithOne("ExecutionInfo")
                        .HasForeignKey("Ares.Messaging.ExecutionInfo", "CommandResultId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Messaging.ExperimentResult", null)
                        .WithOne("ExecutionInfo")
                        .HasForeignKey("Ares.Messaging.ExecutionInfo", "ExperimentResultId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Messaging.StepResult", null)
                        .WithOne("ExecutionInfo")
                        .HasForeignKey("Ares.Messaging.ExecutionInfo", "StepResultId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Messaging.ExperimentExecutionStatus", b =>
                {
                    b.HasOne("Ares.Messaging.CampaignExecutionStatus", null)
                        .WithMany("ExperimentExecutionStatuses")
                        .HasForeignKey("CampaignExecutionStatusUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Messaging.ExperimentResult", b =>
                {
                    b.HasOne("Ares.Messaging.CampaignResult", null)
                        .WithMany("ExperimentResults")
                        .HasForeignKey("CampaignResultUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Messaging.ExperimentTemplate", b =>
                {
                    b.HasOne("Ares.Messaging.CampaignTemplate", null)
                        .WithMany("ExperimentTemplates")
                        .HasForeignKey("CampaignTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ares.Messaging.CompletedExperiment", null)
                        .WithOne("Template")
                        .HasForeignKey("Ares.Messaging.ExperimentTemplate", "CompletedExperimentId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Messaging.Limits", b =>
                {
                    b.HasOne("Ares.Messaging.ParameterMetadata", null)
                        .WithMany("Constraints")
                        .HasForeignKey("ParameterMetadataUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Messaging.OutputMetadata", b =>
                {
                    b.HasOne("Ares.Messaging.CommandMetadata", null)
                        .WithOne("OutputMetadata")
                        .HasForeignKey("Ares.Messaging.OutputMetadata", "UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Messaging.Parameter", b =>
                {
                    b.HasOne("Ares.Messaging.CommandTemplate", null)
                        .WithMany("Parameters")
                        .HasForeignKey("CommandTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ares.Messaging.PlannerResponse", null)
                        .WithMany("PlannedParameters")
                        .HasForeignKey("PlannerResponseUniqueId");

                    b.HasOne("Ares.Messaging.ParameterMetadata", "PlanningMetadata")
                        .WithMany()
                        .HasForeignKey("PlanningMetadataUniqueId");

                    b.Navigation("PlanningMetadata");
                });

            modelBuilder.Entity("Ares.Messaging.ParameterMetadata", b =>
                {
                    b.HasOne("Ares.Messaging.CampaignTemplate", null)
                        .WithMany("PlannableParameters")
                        .HasForeignKey("CampaignTemplateUniqueId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Messaging.CommandMetadata", null)
                        .WithMany("ParameterMetadatas")
                        .HasForeignKey("CommandMetadataUniqueId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Messaging.Parameter", null)
                        .WithOne("Metadata")
                        .HasForeignKey("Ares.Messaging.ParameterMetadata", "ParameterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ares.Messaging.PlannerRequest", null)
                        .WithMany("ParameterMetas")
                        .HasForeignKey("PlannerRequestUniqueId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Messaging.ParameterValue", b =>
                {
                    b.HasOne("Ares.Messaging.Parameter", null)
                        .WithOne("Value")
                        .HasForeignKey("Ares.Messaging.ParameterValue", "ParameterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Messaging.PlannerAllocation", b =>
                {
                    b.HasOne("Ares.Messaging.CampaignTemplate", null)
                        .WithMany("PlannerAllocations")
                        .HasForeignKey("CampaignTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ares.Messaging.ParameterMetadata", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterUniqueId");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("Ares.Messaging.PlannerInfo", b =>
                {
                    b.HasOne("Ares.Messaging.PlannerAllocation", null)
                        .WithOne("Planner")
                        .HasForeignKey("Ares.Messaging.PlannerInfo", "PlannerAllocationId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Messaging.PlannerTransaction", b =>
                {
                    b.HasOne("Ares.Messaging.CompletedExperiment", null)
                        .WithMany("PlannerTransactions")
                        .HasForeignKey("CompletedExperimentUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ares.Messaging.PlannerInfo", "PlannerInfo")
                        .WithMany()
                        .HasForeignKey("PlannerInfoUniqueId");

                    b.HasOne("Ares.Messaging.PlannerRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestUniqueId");

                    b.HasOne("Ares.Messaging.PlannerResponse", "Response")
                        .WithMany()
                        .HasForeignKey("ResponseUniqueId");

                    b.Navigation("PlannerInfo");

                    b.Navigation("Request");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("Ares.Messaging.StepExecutionStatus", b =>
                {
                    b.HasOne("Ares.Messaging.ExperimentExecutionStatus", null)
                        .WithMany("StepExecutionStatuses")
                        .HasForeignKey("ExperimentExecutionStatusUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Messaging.StepResult", b =>
                {
                    b.HasOne("Ares.Messaging.ExperimentResult", null)
                        .WithMany("StepResults")
                        .HasForeignKey("ExperimentResultUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ares.Messaging.StepTemplate", null)
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Messaging.StepTemplate", b =>
                {
                    b.HasOne("Ares.Messaging.ExperimentTemplate", null)
                        .WithMany("StepTemplates")
                        .HasForeignKey("ExperimentTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Google.Protobuf.WellKnownTypes.Any", b =>
                {
                    b.HasOne("Ares.Messaging.CompletedExperiment", null)
                        .WithOne("Result")
                        .HasForeignKey("Google.Protobuf.WellKnownTypes.Any", "CompletedExperimentId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Messaging.DeviceCommandResult", null)
                        .WithOne("Result")
                        .HasForeignKey("Google.Protobuf.WellKnownTypes.Any", "DeviceCommandResultId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Messaging.Device.DeviceConfig", null)
                        .WithOne("ConfigData")
                        .HasForeignKey("Google.Protobuf.WellKnownTypes.Any", "DeviceConfigId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Messaging.Analysis", b =>
                {
                    b.Navigation("Analyzer");
                });

            modelBuilder.Entity("Ares.Messaging.CampaignExecutionStatus", b =>
                {
                    b.Navigation("ExperimentExecutionStatuses");
                });

            modelBuilder.Entity("Ares.Messaging.CampaignResult", b =>
                {
                    b.Navigation("ExecutionInfo");

                    b.Navigation("ExperimentResults");
                });

            modelBuilder.Entity("Ares.Messaging.CampaignTemplate", b =>
                {
                    b.Navigation("ExperimentTemplates");

                    b.Navigation("PlannableParameters");

                    b.Navigation("PlannerAllocations");
                });

            modelBuilder.Entity("Ares.Messaging.CommandMetadata", b =>
                {
                    b.Navigation("OutputMetadata");

                    b.Navigation("ParameterMetadatas");
                });

            modelBuilder.Entity("Ares.Messaging.CommandResult", b =>
                {
                    b.Navigation("ExecutionInfo");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Ares.Messaging.CommandTemplate", b =>
                {
                    b.Navigation("Metadata");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Ares.Messaging.CompletedExperiment", b =>
                {
                    b.Navigation("PlannerTransactions");

                    b.Navigation("Result");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Ares.Messaging.Device.DeviceConfig", b =>
                {
                    b.Navigation("ConfigData");
                });

            modelBuilder.Entity("Ares.Messaging.DeviceCommandResult", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("Ares.Messaging.ExperimentExecutionStatus", b =>
                {
                    b.Navigation("StepExecutionStatuses");
                });

            modelBuilder.Entity("Ares.Messaging.ExperimentResult", b =>
                {
                    b.Navigation("CompletedExperiment");

                    b.Navigation("ExecutionInfo");

                    b.Navigation("StepResults");
                });

            modelBuilder.Entity("Ares.Messaging.ExperimentTemplate", b =>
                {
                    b.Navigation("Analyzer");

                    b.Navigation("StepTemplates");
                });

            modelBuilder.Entity("Ares.Messaging.Parameter", b =>
                {
                    b.Navigation("Metadata");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("Ares.Messaging.ParameterMetadata", b =>
                {
                    b.Navigation("Constraints");
                });

            modelBuilder.Entity("Ares.Messaging.PlannerAllocation", b =>
                {
                    b.Navigation("Planner");
                });

            modelBuilder.Entity("Ares.Messaging.PlannerRequest", b =>
                {
                    b.Navigation("ParameterMetas");
                });

            modelBuilder.Entity("Ares.Messaging.PlannerResponse", b =>
                {
                    b.Navigation("PlannedParameters");
                });

            modelBuilder.Entity("Ares.Messaging.StepExecutionStatus", b =>
                {
                    b.Navigation("CommandExecutionStatuses");
                });

            modelBuilder.Entity("Ares.Messaging.StepResult", b =>
                {
                    b.Navigation("CommandResults");

                    b.Navigation("ExecutionInfo");
                });

            modelBuilder.Entity("Ares.Messaging.StepTemplate", b =>
                {
                    b.Navigation("CommandTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
