<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <AssemblyVersion>0.0.98</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <Version>$(AssemblyVersion)</Version>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Mfc.proto" />
    <None Remove="Proto\MfcConfig.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="UnitsNet" Version="5.75.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.Device.Serial\AresSerial\Ares.Device.Serial.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Proto\Mfc.proto" ProtoRoot="Proto" />
    <Protobuf Include="Proto\MfcConfig.proto" GrpcServices="None" />
  </ItemGroup>

</Project>
