syntax = "proto3";

package ares.messages.device_state;

import "google/protobuf/empty.proto";
import "DeviceState/StateRequestFilter.proto";
import "DeviceStateLogging/DevicesResponse.proto";

service StateExportService {
	// This returns a byte array that is ready to be saved as a specified format
	// ex.: This could return a byte string that represents a zip file
	rpc GetStateExport(StateRequest) returns (StateResponse);
}

message StateRequest {
	StateRequestFilter filter = 1;
	ExportType export_type = 2;
}

enum ExportType {
	UNSPECIFIED = 0;
	COMBINED = 1;
	ZIPPED = 2;
}

message StateResponse {
	bytes data = 1;
}