syntax = "proto3";

package tc0304.data_model;

import "google/protobuf/wrappers.proto";

message Data {
  google.protobuf.DoubleValue t1_probe = 1; // Temperature of the T1 probe in Celsius
  google.protobuf.DoubleValue t2_probe = 2; // Temperature of the T2 probe in Celsius
  google.protobuf.DoubleValue t3_probe = 3; // Temperature of the T3 probe in Celsius
  google.protobuf.DoubleValue t4_probe = 4; // Temperature of the T4 probe in Celsius
  bool battery_low = 5; // True when the battery is low
  Mode mode = 6; // Temperature display mode
  bool t1t2 = 7;
  bool hold = 8; // Temperature is being held
}

message ProbeNames {
  google.protobuf.StringValue t1_name = 1;
  google.protobuf.StringValue t2_name = 2;
  google.protobuf.StringValue t3_name = 3;
  google.protobuf.StringValue t4_name = 4;
}

enum Mode {
  NORMAL = 0;
  MAXIMUM = 1;
  MINIMUM = 2;
  MAX_MIN = 3;
}