syntax = "proto3";

package ares.messages.device_states.tube_furnace;

import "google/protobuf/timestamp.proto";

message TubeFurnaceStateEntity {
  string unique_id = 1; // unique id for this state
  google.protobuf.Timestamp timestamp = 2; // the time at which this state was collected
  string device_id = 3; // the name/id of the tube furnace for which this state belongs to
  double currentTemp = 4; //The current temperature of the Tube Furnace
  double SetPointTemp = 5; //The current furnace set point temperature
}