syntax = "proto3";

package ares.messages.device_states.tube_furnace;

import "google/protobuf/empty.proto";
import "DeviceStateLogging/TubeFurnace/TubeFurnaceStateEntity.proto";
import "device/device_state_request_filter.proto";
import "DeviceStateLogging/DevicesResponse.proto";

service TubeFurnaceStateLogging {
	rpc GetTubeFurnaceStates(datamodel.device.DeviceStateRequestFilter) returns (TubeFurnaceStateResponse);
	rpc DeleteTubeFurnaceStates(datamodel.device.DeviceStateRequestFilter) returns (google.protobuf.Empty);
	rpc GetAvailableDevices(google.protobuf.Empty) returns (DevicesResponse);
}

message TubeFurnaceStateResponse {
	map<string, StateCollection> state_map = 1;
}

message StateCollection {
	repeated TubeFurnaceStateEntity state_logs = 1;
}