syntax = "proto3";

package ares.messages.device_states.tc0304;

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

message Tc0304State {
  string unique_id = 1; // the unique id for this state
  google.protobuf.DoubleValue probe1_temperature = 2; // Temperature (C)
  google.protobuf.DoubleValue probe2_temperature = 3; // Temperature (C)
  google.protobuf.DoubleValue probe3_temperature = 4; // Temperature (C)
  google.protobuf.DoubleValue probe4_temperature = 5; // Temperature (C)
  google.protobuf.Timestamp timestamp = 6;
  string device_id = 7;
}