syntax = "proto3";

package ares.messages.device_states.tc0304;

import "google/protobuf/empty.proto";
import "DeviceStateLogging/Tc0304/Tc0304State.proto";
import "DeviceState/StateRequestFilter.proto";
import "DeviceStateLogging/DevicesResponse.proto";

service Tc0304StateLogging {
	rpc GetStates(device_state.StateRequestFilter) returns (Tc0304StateResponse);
	rpc DeleteStates(device_state.StateRequestFilter) returns (google.protobuf.Empty);
	rpc GetAvailableDevices(google.protobuf.Empty) returns (DevicesResponse);
}

message Tc0304StateResponse {
	map<string, StateCollection> state_map = 1;
}

message StateCollection {
	repeated Tc0304State state_logs = 1;
}