<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!--<ItemGroup>
    <None Remove="Proto\ChillerConfig.proto" />
    <None Remove="Proto\DataModel.proto" />
    <None Remove="Proto\Services.proto" />
  </ItemGroup>-->

  <ItemGroup>
    <PackageReference Include="Ares.Tools" Version="2025.8.4.112732" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.Device.Serial\AresSerial\Ares.Device.Serial.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Proto\ChillerConfig.proto" GrpcServices="None" ProtoRoot="Proto" />
    <Protobuf Include="Proto\DataModel.proto" GrpcServices="None" ProtoRoot="Proto" />
    <Protobuf Include="Proto\Services.proto" ProtoRoot="Proto" />
  </ItemGroup>

</Project>
