<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="LaserChiller\LaserChillerConfigEditView.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Include="LaserChiller\LaserChillerControlWidgetView.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Include="LaserChiller\LaserChillerSettingsList.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Include="LaserChiller\LaserChillerSettingsView.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

  <!--<ItemGroup>
    <None Remove="Proto\ChillerConfig.proto" />
    <None Remove="Proto\DataModel.proto" />
    <None Remove="Proto\Services.proto" />
  </ItemGroup>-->

  <ItemGroup>
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.Device.Serial\AresSerial\Ares.Device.Serial.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Proto\ChillerConfig.proto" GrpcServices="None" ProtoRoot="Proto" />
    <Protobuf Include="Proto\DataModel.proto" GrpcServices="None" ProtoRoot="Proto" />
    <Protobuf Include="Proto\Services.proto" ProtoRoot="Proto" />
  </ItemGroup>

</Project>
