syntax = "proto3";

package ares.messages.device_states.tic_stepper_controller;

import "google/protobuf/timestamp.proto";

message TicStepperControllerState {
  string unique_id = 1; // unique id for this state
  google.protobuf.Timestamp timestamp = 2; // the time at which this state was collected
  string device_id = 3; // the name/id of the TIC controller for which this state belongs to
  uint32 max_acceleration = 4; // microsteps per 100 s²
  uint32 max_deceleration = 5; // microsteps per 100 s²
  uint32 max_speed = 6; // microsteps per 10,000 s
  uint32 starting_speed = 7; // microsteps per 10,000 s
  uint32 custom_step_size = 8; // steps per user defined step (not the stepper motor step)
  StepMode step_mode = 9; // microsteps per stepper defined step
  sint32 current_position = 10; // current assumed position in microsteps
  sint32 target_position = 11; // currently set target position in microsteps
  repeated string status_messages = 12;
}

enum StepMode {
  UNDEFINED = 0;
  STEP1_2 = 1;
  STEP1_4 = 2;
  STEP1_8 = 3;
  STEP1_16 = 4;
  STEP1_32 = 5;
  STEP1_2_100 = 6;
  STEP1_64 = 7;
  STEP1_128 = 8;
  STEP1_256 = 9;
}