syntax = "proto3";

package ares.syringe_pump.ne1000.messaging;

import "google/protobuf/empty.proto";
import "SyringePumpConfig.proto";

service SyringePumpRpc {
	rpc Connect(ConnectRequest) returns (ConnectResponse);
	rpc Disconnect(DeviceRequest) returns (google.protobuf.Empty);

	rpc GetCurrentState(DeviceRequest) returns (StateResponse);

	rpc SetDiameter(SetDiameterMmRequest) returns (google.protobuf.Empty);
	rpc GetDiameter(DeviceRequest) returns (google.protobuf.Empty);
	rpc SetProgramFunctionRate(SetProgramFunctionRateMmpmRequest) returns (google.protobuf.Empty);
	rpc GetProgramFunctionRate(DeviceRequest) returns (google.protobuf.Empty);
	rpc SetProgramFunctionVolumeToBeDispensed(SetProgramFunctionVolumeToBeDispensedRequest) returns (google.protobuf.Empty);
	rpc GetProgramFunctionVolumeToBeDispensed(DeviceRequest) returns (google.protobuf.Empty);
	rpc SetProgramFunctionPumpingDirection(SetProgramFunctionPumpingDirectionRequest) returns (google.protobuf.Empty);
	rpc GetProgramFunctionPumpingDirection(GetProgramFunctionPumpingDirectionRequest) returns (google.protobuf.Empty);
	rpc StartPumpingProgram(DeviceRequest) returns (google.protobuf.Empty);
	rpc PurgePump(DeviceRequest) returns (google.protobuf.Empty);
	rpc StopPumpingProgram(DeviceRequest) returns (google.protobuf.Empty);
	rpc GetVolumeDispensed(DeviceRequest) returns (google.protobuf.Empty);
	rpc ClearVolumeDispensed(ClearVolumeDispensedRequest) returns (google.protobuf.Empty);
	rpc SetAddress(SetAddressRequest) returns (google.protobuf.Empty);
	rpc GetAddress(DeviceRequest) returns (google.protobuf.Empty);
	rpc QueryPhase(DeviceRequest) returns (google.protobuf.Empty);
	rpc QueryPhaseFunction(DeviceRequest) returns (google.protobuf.Empty);
	rpc SetPhase(SetPhaseNumberRequest) returns (google.protobuf.Empty);
	rpc SetPhaseFunction(SetPhaseFunctionRequest) returns (google.protobuf.Empty);

	rpc AddSyringePump(SyringePumpConfig) returns (google.protobuf.Empty);
	rpc RemoveSyringePump(SyringePumpRemoveRequest) returns (google.protobuf.Empty);
	rpc UpdateSyringePump(SyringePumpConfig) returns (google.protobuf.Empty);
	rpc GetAllSyringePumps(google.protobuf.Empty) returns (GetAllSyringePumpsResponse);

}

message ConnectRequest {
	string device_name = 1; // name of the mass flow controller
	string port_name = 2; // name of the port
}

message SyringePumpRemoveRequest {
	string device_id = 1; // id of the syringe pump (name for now)
}

message ConnectResponse {
	bool connected = 1; // whether or not the device successfully connected
}

message DeviceRequest {
	string device_name = 1;
}

message SetDiameterMmRequest {
	DeviceRequest device_request = 1;
	float diameter_mm = 2;
}

message SetProgramFunctionRateMmpmRequest {
	DeviceRequest device_request = 1;
	float rate_mmpm = 2;
}

message SetProgramFunctionVolumeToBeDispensedRequest {
	DeviceRequest device_request = 1;
	float volume_ml = 2;
}

message SetProgramFunctionPumpingDirectionRequest {
	DeviceRequest device_request = 1;
	.ares.syringe_pump.ne1000.messaging.Direction direction = 2;
}

message GetProgramFunctionPumpingDirectionRequest {
	DeviceRequest device_request = 1;
}


message ClearVolumeDispensedRequest {
	DeviceRequest device_request = 1;
	.ares.syringe_pump.ne1000.messaging.Direction direction = 2;
}

message SetAddressRequest {
	DeviceRequest device_request = 1;
	int32 address = 2;
}

message SetPhaseNumberRequest {
	DeviceRequest device_request = 1;
	int32 phase = 2;
}

message SetPhaseFunctionRequest {
	DeviceRequest device_request = 1;
	.ares.syringe_pump.ne1000.messaging.Commands function = 2;
}

enum StatusAlarm {
	UNDEFINED_STATUS_ALARM = 0;
	ALARM_R = 1; // Pump was reset (power was interrupted)
	ALARM_S = 2; // Pump motor stalled
	ALARM_T = 3; // Safe mode communications time out
	ALARM_E = 4; // Pumping Porgram error
	ALARM_O = 5; // Pumping Program Phase is out of range
}

enum CommandError {
	UNDEFINED_ERROR = 0;
	UNRECOGNIZED_COMMAND = 1; // ?
	NA = 2; // Not currently applicable
	OOR = 3; // Out of range
	COM = 4; // Invalid Communications packet received
	IGN = 5; // Ignored due to simultaneous new Phase start
}

enum StatusPrompt {
	UNDEFINED_STATUS_PROMPT = 0;
	PROMPT_I = 1; // Infusing
	PROMPT_W = 2; // Withdrawing
	PROMPT_S = 3; // Pumping Program Stopped
	PROMPT_P = 4; // Pumping Program Paused
	PROMPT_T = 5; // Timed Pause Phase
	PROMPT_U = 6; // Operational Trigger Wait (user wait)
	PROMPT_X = 7; // Purging
}

enum RateUnit {
	UNDEFINED_RATE_UNIT = 0;
	UM = 1; // μL / min
	MM = 2; // mL / min
	UH = 3; // μL / hr
	MH = 4; // mL / hr
}

enum VolumeUnit {
	UNDEFINED_VOLUME_UNIT = 0;
	UL = 1; // μL 
	ML = 2; // mL 
}

enum Direction {
	UNDEFINED_DIRECTION = 0;
	INF = 1; // Infuse
	WDR = 2; // Withdraw
	REV = 3; // Reverse pumping direction
	STK = 4; // "Sticky Direction"
}

enum Commands {
	UNDEFINED_FUNCTION = 0;
	// Phase Functions
		// Rate Data Functions
	// FUN_RAT = 1; // Pumping rate. 'RATE'
	// FUN_FIL = 2; // Fill syringe to dispensed volume. 'FILL'
	// FUN_INC = 3; // Increment rate. 'INCR'
	// FUN_DEC = 4; // Decrement rate. 'DECR'
	// 	// Non-Rate Control Functions
	// FUN_STP = 5; // Stop pump. 'STOP'
	// FUN_PAS = 6; // <number data> Pauses pumping for 'nn' seconds 'PS:nn'. <n.n> Pauses pumping for n.n seconds 'PS:n.n'
	// FUN_PRI = 7; // Sub-Program Selection Input 'PR:In'
	// FUN_PRL = 8; // <number data> Sub-Program Start Label defintion 'PR:nn'
	// FUN_LPS = 9; // Loop starting Phase 'LP:ST'
	// FUN_LPE = 10; // Loop end Phase 'LP:EN'
	// FUN_LOP = 11; // <count data> Loop to previous loop start 'nn' times 'LP:nn'
	// FUN_JMP = 12; // <phase data> Jump to Prgram Phase 'JP:nn'
	// FUN_IF = 13; // <phase data> If Program input TTL pin low, jump to Phase 'IF:nn'
	// FUN_EVN = 14; // <phase data> Set event trigger trap 'EV:nn'
	// FUN_EVR = 15; // Event trigger reset 'EV:RS'
	// FUN_CLD = 16; // Clear total dispense volume 'CLR.D'
	// FUN_TRG = 17; // <nn> Override Operational Trigger Default Mode, set to <nn>, 'tr:aa'
	// FUN_BEP = 18; // Sound short beep 'BEEP'
	// FUN_OUT = 19; // <TTL level> Set programmable output pin 'OUT.n'

	// Diameter
	DIA = 20; // [ <float> ]

	//Phase Number
	PHN = 21; // [ <phase data> ]

	// Pumping Rate
	RAT = 22; // [C|I] [ <float> ] [ <rate units> ]. 'C' Allows the pumping Program to continue after pumping rate is changed. 'I' Changes the pumping rate only if the pump is infusing.
	// Volume to be Dispensed and Set Volume Units
	VOL = 23; // [ <float> | <volume units> ]. Query response: <float> <volume units>
	// Pumping Direction
	DIR = 24; // [ INF | WDR | REV | STK ]. Query response: { INF | WDR | STK }. When set to "Sticky Direction", query will respond with current pumping direction (INF or WDR)

	// Start Pumping Program
	RUN = 25; // [<phase data>] [ E [<phase data>] ]. Starts the Pumping Program operation. Resumes where paused, or starts from Phase 1. Starts from <phase data> if defined. "E" triggers a Pumping Program Event while the Pumping Program is active 

	// Purge Pump
	PUR = 26; // Starts purge. Pump infuses/withdraws at top speed, depending on pumping direction

	// Stop Pumping Program
	STP = 27; // If the Pumping Program is operatiing, the pump will stop and the Program will be paused. If the Program is paused, the pause will cancel and reset Program to phase 1

	// Volume Dispensed
	DIS = 28; // Queries volume dispensed only. Response: I <float> W <float> <volume units> where I is infusion volume dispensed and W is withdrawn volume

	// Clear Volume dispensed
	CLD = 29; // { INF | WDR }. Sets Infused or withdrawn volume dispensed to 0.

	// System Commands
		// Set Pump Network Address and Baud Rate
	ADR = 30; // [ <address> [ B { 19200 | 9600 | 2400 | 1200 | 300 } ] ] [DUAL | RECP | ALTR ]
	RESET = 31; // Resets Pump, clears program memory and resets setup.
	FUN = 32; // Set/Query current phase function
	VER = 33; //Query the firmware version of the syringe pump
}

message Phase {
	int32 number = 1;
	Commands function = 2;
	float rate = 3;
	string unit = 4;
	Direction direction = 5;
}

message StateResponse {
	string firmware_version = 1;
	float dispensed_volume = 2;
	float withdrawn_volume = 3;
	VolumeUnit volume_units = 4;
	RateUnit rate_units = 5;
	int32 address = 6;
	bool safe_mode = 7;
	float diameter_mm = 8;
	Phase phase = 9;
	StatusPrompt status = 10;
	string deviceId = 11;
}

message SyringePumpDeviceDescription {
	string name = 1;
	int32 assumed_address = 2;
}

message GetAllSyringePumpsResponse {
	repeated SyringePumpDeviceDescription syringe_pumps = 1;
}
