syntax = "proto3";

option csharp_namespace = "DemoDevice";

import "google/protobuf/empty.proto";

package demo_device;

service DemoDeviceGrpc {
  rpc SetTemperature (Temperature) returns (google.protobuf.Empty);
  rpc GetTemperature (google.protobuf.Empty) returns (Temperature);
  rpc GetCurrentGrowth (google.protobuf.Empty) returns (GrowthResponse);
  rpc GetCurrentPillar (google.protobuf.Empty) returns (CurrentPillarResponse);
  rpc MoveToNextPillar (google.protobuf.Empty) returns (CurrentPillarResponse);
}

message Temperature {
  double value = 1;
}

message GrowthResponse {
  double growth = 1;
}

message CurrentPillarResponse {
  sint32 pillar = 1;
}
