<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;DEBUG;SIM</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.28">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.28" />
    <PackageReference Include="morelinq" Version="4.1.0" />
    <PackageReference Include="UnitsNet" Version="5.49.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlicatMFC\AlicatMFC.csproj" />
    <ProjectReference Include="..\Ares.Core\Ares.Core.csproj" />
    <ProjectReference Include="..\Ares.DataModel.Grpc\Ares.DataModel.Grpc.csproj" />
    <ProjectReference Include="..\Ares.DataModel\Ares.DataModel.csproj" />
    <ProjectReference Include="..\HerkulexDRS\HerkulexDRS.csproj" />
    <ProjectReference Include="..\LindbergFurnace\LindbergFurnace.csproj" />
    <ProjectReference Include="..\SyringePumpNE1000\SyringePumpNE1000.csproj" />
    <ProjectReference Include="..\TC0304\TC0304.csproj" />
    <ProjectReference Include="..\TicStepperController\TicStepperController.csproj" />
    <ProjectReference Include="..\ValveController\ValveController.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

</Project>
