<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Proto\SyringePump.proto" />
    <None Remove="Proto\SyringePumpConfig.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ares.Tools" Version="2025.8.4.112732" />
    <PackageReference Include="Crc32.NET" Version="1.2.0" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NullFX.CRC" Version="1.1.10" />
    <PackageReference Include="UnitsNet" Version="5.75.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.Device.Serial\AresSerial\Ares.Device.Serial.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Proto\SyringePump.proto" ProtoRoot="Proto" />
    <Protobuf Include="Proto\SyringePumpConfig.proto" GrpcServices="None" />
    <Protobuf Include="Proto\DataModel.proto" GrpcServices="None" />
  </ItemGroup>

</Project>
