syntax = "proto3";

package rest_serial_device.services;

import "google/protobuf/empty.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/wrappers.proto";
import "DataModel.proto";
import "RestSerialConfig.proto";

service RestSerialDeviceRpc {
	rpc GetData(DeviceRequest) returns (DataResponse);
	rpc StartStateUpdater(StartStateUpdaterRequest) returns (google.protobuf.Empty);
	rpc StopStateUpdater(DeviceRequest) returns (google.protobuf.Empty);

	rpc GetAllGenericSerialDevices(google.protobuf.Empty) returns (GetAllGenericSerialDevicesResponse);
	rpc UpdateGenericSerialDevice(GenericSerialRestDeviceUpdateRequest) returns (google.protobuf.Empty);
	rpc RemoveGenericSerialDevice(DeviceRequest) returns (google.protobuf.Empty);
	rpc AddGenericSerialDevice(config.RestSerialConfig) returns (google.protobuf.Empty);

	rpc GetDeviceCapabilities(DeviceRequest) returns (DeviceCapabilitiesResponse);
	rpc CallDeviceMethod(DeviceMethodRequest) returns (DeviceMethodResponse);

	rpc GetAvailableSerialPorts(google.protobuf.Empty) returns (AvailableSerialPortsResponse);
}

message GenericSerialRestDeviceUpdateRequest {
	string id = 1;
	config.RestSerialConfig config = 2;
}

message AvailableSerialPortsResponse {
	repeated string port_names = 1;
}

message DeviceRequest {
	string device_id = 1;
}

message DataResponse {
	rest_serial_device.data_model.Data data = 1;
}

message StartStateUpdaterRequest {
	DeviceRequest device_request = 1;
	google.protobuf.Duration interval = 2;
}

message GetAllGenericSerialDevicesResponse {
	repeated DeviceDescription devices = 1;
}

message DeviceDescription {
	string id = 1;
	string name = 2;
}

message DeviceCapabilitiesResponse {
	string device_id = 1;
	repeated DeviceMethodInfo device_methods = 2; // Refers to the new DeviceMethodInfo message
}

message DeviceMethodRequest {
	string device_id = 1;
	string method_name = 2;
	repeated string parameter_names = 3;
	repeated string parameter_values = 4;
}


message DeviceMethodResponse {
	oneof value {
		string string_value = 1;
		double double_value = 2;
		bool bool_value = 3;
		bytes bytes_value = 4;
	}
	bool success = 5; // To indicate if the method call was successful
}

message DeviceMethodInfo {
	string method_name = 1;
	repeated string parameters = 2;
}

/*
message DeviceParameterInfo { // <--- NEW MESSAGE DEFINITION
	string name = 1;
	string unit = 2;
	google.protobuf.DoubleValue minimum = 3; // Optional double using wrapper
	google.protobuf.DoubleValue maximum = 4; // Optional double using wrapper
}*/
