<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Proto\DataModel.proto" />
    <None Remove="Proto\Services.proto" />
    <None Remove="Proto\VerdiConfig.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.33.1" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="Proto\DataModel.proto" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.Device.Serial\AresSerial\Ares.Device.Serial.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Proto\Services.proto" ProtoRoot="Proto" />
    <Protobuf Include="Proto\VerdiConfig.proto" GrpcServices="None" />
		<Protobuf Include="Proto\DataModel.proto" GrpcServices="None" />
  </ItemGroup>

</Project>
