// <auto-generated />
using System;
using AresService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AresService.Migrations.SqlServer.Migrations.AresDb
{
    [DbContext(typeof(AresDbContext))]
    [Migration("20260723132659_analyzer_map_template_fix_AresDbContext")]
    partial class analyzer_map_template_fix_AresDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ares.Datamodel.AnalysisOverview", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalyzerInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("ExperimentOverviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<double>("Result")
                        .HasColumnType("float");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentOverviewId")
                        .IsUnique()
                        .HasFilter("[ExperimentOverviewId] IS NOT NULL");

                    b.ToTable("AnalysisOverview");
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.Analysis", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnalysisOutcome")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ErrorString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<float>("Result")
                        .HasColumnType("real");

                    b.HasKey("UniqueId");

                    b.ToTable("Analyses", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerCapabilities", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalyzerInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("SettingsSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeoutSeconds")
                        .HasColumnType("bigint");

                    b.HasKey("UniqueId");

                    b.HasIndex("AnalyzerInfoId")
                        .IsUnique();

                    b.ToTable("AnalyzerCapabilities");
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerConfig", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("Analyzers", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerInfo", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("AnalyzerInfos");
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerSettings", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalyzerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("AnalyzerSettings");
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerTransaction", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalysisResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalyzerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalyzerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalyzerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalyzerVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("TimeRequestSent")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeResponseReceived")
                        .HasColumnType("datetime2");

                    b.HasKey("UniqueId");

                    b.ToTable("AnalyzerTransactions");
                });

            modelBuilder.Entity("Ares.Datamodel.AresCampaignTag", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("TagName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("CampaignTags");
                });

            modelBuilder.Entity("Ares.Datamodel.AresGeneralSettingsConfig", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandLatency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommandRetryLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ExperimentRetryLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("RetryCooldown")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("AresGeneralSettingsConfig", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Automation.CustomCommand", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CurrentVersionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("UniqueId");

                    b.ToTable("CustomCommands", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Automation.CustomCommandParameter", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CustomCommandVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schema")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("CustomCommandVersionId");

                    b.ToTable("CustomCommandParameters", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Automation.CustomCommandVersion", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CustomCommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScriptBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("VersionNumber")
                        .HasColumnType("bigint");

                    b.HasKey("UniqueId");

                    b.HasIndex("CustomCommandId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("CustomCommandVersions", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.CampaignExecutionSummary", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CampaignId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampaignNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampaignTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CloseoutExecutionSummaryUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("StartupExecutionSummaryUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UniqueId");

                    b.HasIndex("CloseoutExecutionSummaryUniqueId");

                    b.HasIndex("StartupExecutionSummaryUniqueId");

                    b.ToTable("CampaignExecutionSummaries", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.CommandExecutionStatus", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StepExecutionStatusUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VariableName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("StepExecutionStatusUniqueId");

                    b.ToTable("CommandExecutionStatuses", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.CommandExecutionSummary", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<Guid?>("StepExecutionSummaryUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TemplateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("StepExecutionSummaryUniqueId");

                    b.ToTable("CommandExecutionSummaries", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.CommandResult", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AwaitUserInput")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CommandExecutionSummaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("UniqueId");

                    b.HasIndex("CommandExecutionSummaryId")
                        .IsUnique()
                        .HasFilter("[CommandExecutionSummaryId] IS NOT NULL");

                    b.ToTable("DeviceCommandResults", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceCommandDescriptor", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeviceInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InputSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputSchema")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("DeviceInfoId");

                    b.ToTable("DeviceCommandDescriptor");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceConfig", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceSettings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSimulated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("SerialInfoUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UniqueId");

                    b.HasIndex("SerialInfoUniqueId");

                    b.ToTable("DeviceConfigs", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceInfo", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingsSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("DeviceInfos");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceLoggingSettings", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Deltas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IntervalMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("LoggingEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("LoggingType")
                        .HasColumnType("int");

                    b.HasKey("UniqueId");

                    b.ToTable("DeviceLoggingSettings");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceSettings", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("DeviceSettings");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceState", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("UniqueId");

                    b.ToTable("DeviceStates");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.RemoteDeviceConfig", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("RemoteDevices", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Device.SerialConnection", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BaudRate")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("PortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("SerialConnection");
                });

            modelBuilder.Entity("Ares.Datamodel.DeviceErrorHandlingConfig", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("Handling")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("UniqueId");

                    b.ToTable("ErrorHandlingConfigs", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.ExecutionInfo", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignExecutionSummaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommandExecutionSummaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("ExperimentResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LocaltimeOffset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StepExecutionSummaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TimeFinished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Timezone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignExecutionSummaryId")
                        .IsUnique()
                        .HasFilter("[CampaignExecutionSummaryId] IS NOT NULL");

                    b.HasIndex("CommandExecutionSummaryId")
                        .IsUnique()
                        .HasFilter("[CommandExecutionSummaryId] IS NOT NULL");

                    b.HasIndex("ExperimentResultId")
                        .IsUnique()
                        .HasFilter("[ExperimentResultId] IS NOT NULL");

                    b.HasIndex("StepExecutionSummaryId")
                        .IsUnique()
                        .HasFilter("[StepExecutionSummaryId] IS NOT NULL");

                    b.ToTable("ExecutionInfos", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentExecutionSummary", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignExecutionSummaryUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ExperimentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ResultOutputPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignExecutionSummaryUniqueId");

                    b.ToTable("ExperimentExecutionSummaries", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentOverview", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("ExperimentResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TemplateUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentResultId")
                        .IsUnique()
                        .HasFilter("[ExperimentResultId] IS NOT NULL");

                    b.HasIndex("TemplateUniqueId");

                    b.ToTable("ExperimentOverviews", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Limits", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<double>("Maximum")
                        .HasColumnType("float");

                    b.Property<double>("Minimum")
                        .HasColumnType("float");

                    b.Property<Guid>("ParameterMetadataUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UniqueId");

                    b.HasIndex("ParameterMetadataUniqueId");

                    b.ToTable("Limits");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.Planner", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("PlannerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PlannerServiceCapabilitiesUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("PlannerServiceCapabilitiesUniqueId");

                    b.ToTable("Planner");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerAllocation", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignTemplateUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("ParameterUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlannerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignTemplateUniqueId");

                    b.HasIndex("ParameterUniqueId");

                    b.HasIndex("PlannerId");

                    b.ToTable("PlannerAllocations", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerConfig", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("PlannerServices", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerServiceCapabilities", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("PlannerInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingsSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeoutSeconds")
                        .HasColumnType("bigint");

                    b.HasKey("UniqueId");

                    b.HasIndex("PlannerInfoId")
                        .IsUnique();

                    b.ToTable("PlannerServiceCapabilities");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerServiceInfo", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("PlannerInfos");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerSettings", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("PlannerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("PlannerSettings");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerTransaction", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("PlannerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlannerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlannerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlannerVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanningRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanningResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeRequestSent")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeResponseReceived")
                        .HasColumnType("datetime2");

                    b.HasKey("UniqueId");

                    b.ToTable("PlannerTransactions");
                });

            modelBuilder.Entity("Ares.Datamodel.Project", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.StepExecutionStatus", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("StepId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StepName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("StepExecutionStatuses", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.StepExecutionSummary", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("ExperimentExecutionSummaryUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("StepId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentExecutionSummaryUniqueId");

                    b.ToTable("StepExecutionSummaries", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CampaignTemplate", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniqueId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("CampaignTemplates", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CommandMetadata", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DeviceCommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("DeviceCommandId")
                        .IsUnique()
                        .HasFilter("[DeviceCommandId] IS NOT NULL");

                    b.ToTable("CommandMetadata");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CommandTemplate", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("OutputVarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StepTemplateUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UniqueId");

                    b.HasIndex("StepTemplateUniqueId");

                    b.ToTable("CommandTemplates", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.DeviceCommand", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommandTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("UniqueId");

                    b.HasIndex("CommandTemplateId")
                        .IsUnique()
                        .HasFilter("[CommandTemplateId] IS NOT NULL");

                    b.ToTable("DeviceCommands", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.ExperimentTemplate", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalyzerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalyzerMaps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CampaignCloseoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignStartupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignCloseoutId")
                        .IsUnique()
                        .HasFilter("[CampaignCloseoutId] IS NOT NULL");

                    b.HasIndex("CampaignExperimentId")
                        .IsUnique()
                        .HasFilter("[CampaignExperimentId] IS NOT NULL");

                    b.HasIndex("CampaignStartupId")
                        .IsUnique()
                        .HasFilter("[CampaignStartupId] IS NOT NULL");

                    b.ToTable("ExperimentTemplates", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.OutputMetadata", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DataSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("UniqueId");

                    b.ToTable("OutputMetadata");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.Parameter", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommandTemplateUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("ExperimentOverviewUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("SourceJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Source");

                    b.HasKey("UniqueId");

                    b.HasIndex("CommandTemplateUniqueId");

                    b.HasIndex("ExperimentOverviewUniqueId");

                    b.ToTable("Parameters", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.ParameterMetadata", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignTemplateUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommandMetadataUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("InitialValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotPlannable")
                        .HasColumnType("bit");

                    b.Property<string>("OutputName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlannerDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlannerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UseDefault")
                        .HasColumnType("bit");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignTemplateUniqueId");

                    b.HasIndex("CommandMetadataUniqueId");

                    b.HasIndex("ParameterId")
                        .IsUnique()
                        .HasFilter("[ParameterId] IS NOT NULL");

                    b.ToTable("ParameterMetadata");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.StepTemplate", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("ExperimentTemplateUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsParallel")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentTemplateUniqueId");

                    b.ToTable("StepTemplates", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Visualizing.Local.DeviceVisualizationConfig", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChartTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("GridH")
                        .HasColumnType("int");

                    b.Property<int>("GridW")
                        .HasColumnType("int");

                    b.Property<int>("GridX")
                        .HasColumnType("int");

                    b.Property<int>("GridY")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("NumberDisplayPoints")
                        .HasColumnType("int");

                    b.Property<string>("Paths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PollingRate")
                        .HasColumnType("int");

                    b.Property<bool>("ShowDataLabels")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowMarkers")
                        .HasColumnType("bit");

                    b.Property<int>("Style")
                        .HasColumnType("int");

                    b.HasKey("UniqueId");

                    b.ToTable("DeviceVisualizationConfigs");
                });

            modelBuilder.Entity("Ares.Datamodel.Visualizing.Local.VisualizationPath", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssociatedDeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlottable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("VisualizationPath");
                });

            modelBuilder.Entity("Ares.Services.DriverInfo", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("DeviceDrivers");
                });

            modelBuilder.Entity("Ares.Datamodel.AnalysisOverview", b =>
                {
                    b.HasOne("Ares.Datamodel.ExperimentOverview", null)
                        .WithOne("AnalysisOverview")
                        .HasForeignKey("Ares.Datamodel.AnalysisOverview", "ExperimentOverviewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerCapabilities", b =>
                {
                    b.HasOne("Ares.Datamodel.Analyzing.AnalyzerInfo", null)
                        .WithOne("Capabilities")
                        .HasForeignKey("Ares.Datamodel.Analyzing.AnalyzerCapabilities", "AnalyzerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.Automation.CustomCommandParameter", b =>
                {
                    b.HasOne("Ares.Datamodel.Automation.CustomCommandVersion", null)
                        .WithMany("InputParameters")
                        .HasForeignKey("CustomCommandVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.Automation.CustomCommandVersion", b =>
                {
                    b.HasOne("Ares.Datamodel.Automation.CustomCommand", null)
                        .WithMany()
                        .HasForeignKey("CustomCommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.CampaignExecutionSummary", b =>
                {
                    b.HasOne("Ares.Datamodel.ExperimentExecutionSummary", "CloseoutExecutionSummary")
                        .WithMany()
                        .HasForeignKey("CloseoutExecutionSummaryUniqueId");

                    b.HasOne("Ares.Datamodel.ExperimentExecutionSummary", "StartupExecutionSummary")
                        .WithMany()
                        .HasForeignKey("StartupExecutionSummaryUniqueId");

                    b.Navigation("CloseoutExecutionSummary");

                    b.Navigation("StartupExecutionSummary");
                });

            modelBuilder.Entity("Ares.Datamodel.CommandExecutionStatus", b =>
                {
                    b.HasOne("Ares.Datamodel.StepExecutionStatus", null)
                        .WithMany("CommandExecutionStatuses")
                        .HasForeignKey("StepExecutionStatusUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.CommandExecutionSummary", b =>
                {
                    b.HasOne("Ares.Datamodel.StepExecutionSummary", null)
                        .WithMany("CommandSummaries")
                        .HasForeignKey("StepExecutionSummaryUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.CommandResult", b =>
                {
                    b.HasOne("Ares.Datamodel.CommandExecutionSummary", null)
                        .WithOne("Result")
                        .HasForeignKey("Ares.Datamodel.CommandResult", "CommandExecutionSummaryId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceCommandDescriptor", b =>
                {
                    b.HasOne("Ares.Datamodel.Device.DeviceInfo", null)
                        .WithMany("Commands")
                        .HasForeignKey("DeviceInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceConfig", b =>
                {
                    b.HasOne("Ares.Datamodel.Device.SerialConnection", "SerialInfo")
                        .WithMany()
                        .HasForeignKey("SerialInfoUniqueId");

                    b.Navigation("SerialInfo");
                });

            modelBuilder.Entity("Ares.Datamodel.ExecutionInfo", b =>
                {
                    b.HasOne("Ares.Datamodel.CampaignExecutionSummary", null)
                        .WithOne("ExecutionInfo")
                        .HasForeignKey("Ares.Datamodel.ExecutionInfo", "CampaignExecutionSummaryId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Datamodel.CommandExecutionSummary", null)
                        .WithOne("ExecutionInfo")
                        .HasForeignKey("Ares.Datamodel.ExecutionInfo", "CommandExecutionSummaryId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Datamodel.ExperimentExecutionSummary", null)
                        .WithOne("ExecutionInfo")
                        .HasForeignKey("Ares.Datamodel.ExecutionInfo", "ExperimentResultId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Datamodel.StepExecutionSummary", null)
                        .WithOne("ExecutionInfo")
                        .HasForeignKey("Ares.Datamodel.ExecutionInfo", "StepExecutionSummaryId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentExecutionSummary", b =>
                {
                    b.HasOne("Ares.Datamodel.CampaignExecutionSummary", null)
                        .WithMany("ExperimentSummaries")
                        .HasForeignKey("CampaignExecutionSummaryUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentOverview", b =>
                {
                    b.HasOne("Ares.Datamodel.ExperimentExecutionSummary", null)
                        .WithOne("ExperimentOverview")
                        .HasForeignKey("Ares.Datamodel.ExperimentOverview", "ExperimentResultId");

                    b.HasOne("Ares.Datamodel.Templates.ExperimentTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateUniqueId");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Ares.Datamodel.Limits", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.ParameterMetadata", null)
                        .WithMany("Constraints")
                        .HasForeignKey("ParameterMetadataUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.Planner", b =>
                {
                    b.HasOne("Ares.Datamodel.Planning.PlannerServiceCapabilities", null)
                        .WithMany("AvailablePlanners")
                        .HasForeignKey("PlannerServiceCapabilitiesUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerAllocation", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.CampaignTemplate", null)
                        .WithMany("PlannerAllocations")
                        .HasForeignKey("CampaignTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ares.Datamodel.Templates.ParameterMetadata", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterUniqueId");

                    b.HasOne("Ares.Datamodel.Planning.PlannerServiceInfo", "Planner")
                        .WithMany()
                        .HasForeignKey("PlannerId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Parameter");

                    b.Navigation("Planner");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerServiceCapabilities", b =>
                {
                    b.HasOne("Ares.Datamodel.Planning.PlannerServiceInfo", null)
                        .WithOne("Capabilities")
                        .HasForeignKey("Ares.Datamodel.Planning.PlannerServiceCapabilities", "PlannerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.StepExecutionSummary", b =>
                {
                    b.HasOne("Ares.Datamodel.ExperimentExecutionSummary", null)
                        .WithMany("StepSummaries")
                        .HasForeignKey("ExperimentExecutionSummaryUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CommandMetadata", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.DeviceCommand", null)
                        .WithOne("Metadata")
                        .HasForeignKey("Ares.Datamodel.Templates.CommandMetadata", "DeviceCommandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CommandTemplate", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.StepTemplate", null)
                        .WithMany("CommandTemplates")
                        .HasForeignKey("StepTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Ares.Datamodel.Templates.CustomCommandInvocation", "CustomCommandInvocation", b1 =>
                        {
                            b1.Property<Guid>("CommandTemplateUniqueId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CustomCommandId")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CommandTemplateUniqueId");

                            b1.ToTable("CommandTemplates");

                            b1.WithOwner()
                                .HasForeignKey("CommandTemplateUniqueId");
                        });

                    b.OwnsOne("Ares.Datamodel.Templates.SystemCommand", "SystemCommand", b1 =>
                        {
                            b1.Property<Guid>("CommandTemplateUniqueId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Operation")
                                .HasColumnType("int");

                            b1.HasKey("CommandTemplateUniqueId");

                            b1.ToTable("CommandTemplates");

                            b1.WithOwner()
                                .HasForeignKey("CommandTemplateUniqueId");
                        });

                    b.Navigation("CustomCommandInvocation");

                    b.Navigation("SystemCommand");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.DeviceCommand", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.CommandTemplate", null)
                        .WithOne("DeviceCommand")
                        .HasForeignKey("Ares.Datamodel.Templates.DeviceCommand", "CommandTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.ExperimentTemplate", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.CampaignTemplate", null)
                        .WithOne("CloseoutTemplate")
                        .HasForeignKey("Ares.Datamodel.Templates.ExperimentTemplate", "CampaignCloseoutId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ares.Datamodel.Templates.CampaignTemplate", null)
                        .WithOne("ExperimentTemplate")
                        .HasForeignKey("Ares.Datamodel.Templates.ExperimentTemplate", "CampaignExperimentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ares.Datamodel.Templates.CampaignTemplate", null)
                        .WithOne("StartupTemplate")
                        .HasForeignKey("Ares.Datamodel.Templates.ExperimentTemplate", "CampaignStartupId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.OutputMetadata", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.CommandMetadata", null)
                        .WithOne("OutputMetadata")
                        .HasForeignKey("Ares.Datamodel.Templates.OutputMetadata", "UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.Parameter", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.CommandTemplate", null)
                        .WithMany("ArgumentBindings")
                        .HasForeignKey("CommandTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ares.Datamodel.ExperimentOverview", null)
                        .WithMany("Parameters")
                        .HasForeignKey("ExperimentOverviewUniqueId");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.ParameterMetadata", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.CampaignTemplate", null)
                        .WithMany("PlannableParameters")
                        .HasForeignKey("CampaignTemplateUniqueId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Datamodel.Templates.CommandMetadata", null)
                        .WithMany("ParameterMetadatas")
                        .HasForeignKey("CommandMetadataUniqueId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Datamodel.Templates.Parameter", null)
                        .WithOne("Metadata")
                        .HasForeignKey("Ares.Datamodel.Templates.ParameterMetadata", "ParameterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.StepTemplate", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.ExperimentTemplate", null)
                        .WithMany("StepTemplates")
                        .HasForeignKey("ExperimentTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerInfo", b =>
                {
                    b.Navigation("Capabilities");
                });

            modelBuilder.Entity("Ares.Datamodel.Automation.CustomCommandVersion", b =>
                {
                    b.Navigation("InputParameters");
                });

            modelBuilder.Entity("Ares.Datamodel.CampaignExecutionSummary", b =>
                {
                    b.Navigation("ExecutionInfo");

                    b.Navigation("ExperimentSummaries");
                });

            modelBuilder.Entity("Ares.Datamodel.CommandExecutionSummary", b =>
                {
                    b.Navigation("ExecutionInfo");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceInfo", b =>
                {
                    b.Navigation("Commands");
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentExecutionSummary", b =>
                {
                    b.Navigation("ExecutionInfo");

                    b.Navigation("ExperimentOverview");

                    b.Navigation("StepSummaries");
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentOverview", b =>
                {
                    b.Navigation("AnalysisOverview");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerServiceCapabilities", b =>
                {
                    b.Navigation("AvailablePlanners");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerServiceInfo", b =>
                {
                    b.Navigation("Capabilities");
                });

            modelBuilder.Entity("Ares.Datamodel.StepExecutionStatus", b =>
                {
                    b.Navigation("CommandExecutionStatuses");
                });

            modelBuilder.Entity("Ares.Datamodel.StepExecutionSummary", b =>
                {
                    b.Navigation("CommandSummaries");

                    b.Navigation("ExecutionInfo");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CampaignTemplate", b =>
                {
                    b.Navigation("CloseoutTemplate");

                    b.Navigation("ExperimentTemplate");

                    b.Navigation("PlannableParameters");

                    b.Navigation("PlannerAllocations");

                    b.Navigation("StartupTemplate");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CommandMetadata", b =>
                {
                    b.Navigation("OutputMetadata");

                    b.Navigation("ParameterMetadatas");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CommandTemplate", b =>
                {
                    b.Navigation("ArgumentBindings");

                    b.Navigation("DeviceCommand");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.DeviceCommand", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.ExperimentTemplate", b =>
                {
                    b.Navigation("StepTemplates");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.Parameter", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.ParameterMetadata", b =>
                {
                    b.Navigation("Constraints");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.StepTemplate", b =>
                {
                    b.Navigation("CommandTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
