syntax = "proto3";

package chiller.services;

import "google/protobuf/empty.proto";
import "DataModel.proto";
import "ChillerConfig.proto";

service ChillerRpc {
	rpc SetChillerTemperature(SetChillerTemperatureRequest) returns (google.protobuf.Empty);
	rpc SetChillerRunMode(ChillerRequest) returns (google.protobuf.Empty);
	rpc SetChillerStandbyMode(ChillerRequest) returns (google.protobuf.Empty);
	rpc GetManifoldTemperature(ChillerRequest) returns (ManifoldTemperatureResponse);

	rpc UpdateChiller(UpdateChillerRequest) returns (google.protobuf.Empty);
	rpc RemoveChiller(ChillerRequest) returns (google.protobuf.Empty);
	rpc AddChiller(config.ChillerConfig) returns (google.protobuf.Empty);
	rpc GetAllChillers(google.protobuf.Empty) returns (GetAllChillersResponse);
}

message ChillerRequest {
	string chiller_id = 1;
}

message UpdateChillerRequest {
	string chiller_id = 1;
	config.ChillerConfig config = 2;
}

message SetChillerTemperatureRequest {
	string chiller_id = 1;
	double desired_temperature = 2;
}

message ManifoldTemperatureResponse {
	double manifold_temperature = 1;
}

message GetAllChillersResponse {
	repeated ChillerDescription chillers = 1;
}

message ChillerDescription {
	string id = 1;
	string name = 2;
}

