syntax = "proto3";

package ares.messages.device_states.syringe_pump;

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

message SyringePumpState {
  string unique_id = 1; // unique id for this state
  google.protobuf.Timestamp timestamp = 2; // the time at which this state was collected
  string device_id = 3; // the name/id of the syringe pump for which this state belongs to
  google.protobuf.DoubleValue dispensed_volume = 4;
  google.protobuf.DoubleValue withdrawn_volume = 5;
	VolumeUnit volume_unit = 6;
	RateUnit rate_unit = 7;
	sint32 address = 8;
	Status status = 9;
}

enum RateUnit {
	UNDEFINED_RATE_UNIT = 0;
	MICROLITERS_PER_MINUTE = 1; // μL / min
	MILLILITERS_PER_MINUTE = 2; // mL / min
	MICROLITERS_PER_HOUR = 3; // μL / hr
	MILLILITERS_PER_HOUR = 4; // mL / hr
}

enum VolumeUnit {
	UNDEFINED_VOLUME_UNIT = 0;
	MICROLITERS = 1; // μL 
	MILLILITERS = 2; // mL 
}

enum Status {
	UNDEFINED = 0;
	INFUSING = 1; // Infusing
	WITHDRAWING = 2; // Withdrawing
	PUMPING_STOPPED = 3; // Pumping Program Stopped
	PUMPING_PAUSED = 4; // Pumping Program Paused
	TIMED_PAUSE_PHASE = 5; // Timed Pause Phase
	OPERATIONAL_TRIGGER_WAIT = 6; // Operational Trigger Wait (user wait)
	PURGING = 7; // Purging
}