syntax = "proto3";

package ares.messages.device_states.syringe_pump;

import "google/protobuf/empty.proto";
import "DeviceStateLogging/SyringePump/SyringePumpState.proto";
import "DeviceState/StateRequestFilter.proto";
import "DeviceStateLogging/DevicesResponse.proto";

service SyringePumpStateLogging {
	rpc GetSyringePumpStates(device_state.StateRequestFilter) returns (SyringePumpStateResponse);
	rpc DeleteSyringePumpStates(device_state.StateRequestFilter) returns (google.protobuf.Empty);
	rpc GetAvailableDevices(google.protobuf.Empty) returns (DevicesResponse);
}

message SyringePumpStateResponse {
	map<string, StateCollection> state_map = 1;
}

message StateCollection {
	repeated SyringePumpState state_logs = 1;
}