syntax = "proto3";

package ares.messages.device_states.mfc;

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

message MfcState {
  string unique_id = 1; // the unique id for this state
  google.protobuf.DoubleValue absolute_pressure = 2; // Absolute pressure (PSI)
  google.protobuf.DoubleValue temperature = 3; // Temperature (C)
  google.protobuf.DoubleValue volumetric_flow = 4; // Volumetric flow (CCM)
  google.protobuf.DoubleValue mass_flow = 5; // Mass flow (SCCM)
  google.protobuf.DoubleValue setpoint = 6; // Targeted mass flow (SCCM)
	string gas = 7; // Gas abbreviation (ex: "N2")
	repeated string status_codes = 8; // status codes of the mfc
  google.protobuf.Timestamp timestamp = 9;
  string device_id = 10;
}