syntax = "proto3";

package ares.messages.device_states.mfc;

import "google/protobuf/empty.proto";
import "DeviceStateLogging/Mfc/MfcState.proto";
import "device/state_request_filter.proto";
import "DeviceStateLogging/DevicesResponse.proto";

service MfcStateLogging {
	rpc GetMfcStates(datamodel.device.StateRequestFilter) returns (MfcStateResponse);
	rpc DeleteMfcStates(datamodel.device.StateRequestFilter) returns (google.protobuf.Empty);
	rpc GetAvailableDevices(google.protobuf.Empty) returns (DevicesResponse);
}

message MfcStateResponse {
	map<string, StateCollection> state_map = 1;
}

message StateCollection {
	repeated MfcState state_logs = 1;
}