syntax = "proto3";

package VerdiV6.services;

import "google/protobuf/empty.proto";
import "VerdiConfig.proto";

service VerdiV6Rpc {
	rpc GetLaserShutter(DeviceRequest) returns (GetShutterResponse);
	rpc SetLaserShutter(SetShutterRequest) returns (google.protobuf.Empty);
	rpc GetLaserPower(DeviceRequest) returns (GetLaserPowerResponse);
	rpc SetLaserPower(SetLaserPowerRequest) returns (google.protobuf.Empty);
	rpc ActivateLaser(DeviceRequest) returns (google.protobuf.Empty);
	rpc DeactivateLaser(DeviceRequest) returns (google.protobuf.Empty);

	rpc AddLaser(config.VerdiConfig) returns (google.protobuf.Empty);
	rpc RemoveLaser(DeviceRequest) returns (google.protobuf.Empty);
	rpc GetAllLasers(google.protobuf.Empty) returns (GetAllLasersResponse);
	rpc UpdateLaser(LaserUpdateRequest) returns (google.protobuf.Empty);
}

message LaserUpdateRequest {
	string id = 1;
	config.VerdiConfig config = 2;
}

message DeviceRequest {
	string device_id = 1;
}

message GetShutterResponse {
	bool shutter = 1;
}

message SetShutterRequest {
	string device_id = 1;
	bool shutter = 2;
}

message SetLaserPowerRequest {
	string device_id = 1;
	double laser_power = 2;
}

message GetLaserPowerResponse {
	double laser_power = 1;
}

message GetAllLasersResponse {
	repeated DeviceDescription devices = 1;
}

message DeviceDescription {
	string id = 1;
	string name = 2;
}