<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Protos\BoraasPlanner.proto" />
  </ItemGroup>

  <PropertyGroup>
    <DataModelProtoPath>$(PkgARES_Datamodel)\Proto\datamodel\</DataModelProtoPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ARES.Datamodel" Version="0.5.0-beta" GeneratePathProperty="True"/>
    <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="morelinq" Version="4.4.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.Core\Ares.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\BoraasPlanner.proto" GrpcServices="Client">
      <AdditionalImportDirs>$(DataModelProtoPath)</AdditionalImportDirs>
      <Generator>MSBuild:Compile</Generator>
    </Protobuf>
  </ItemGroup>

</Project>
