syntax = "proto3";

package tic_stepper_controller.config;

import "google/protobuf/wrappers.proto";
import "StepMode.proto";

message StepperControllerConfig {
  string name = 1; // name of the controller
  string port_name = 2; // the port name for the controller to connect to
  google.protobuf.UInt32Value max_acceleration = 3; // microsteps per 100 s²
  google.protobuf.UInt32Value max_deceleration = 4; // microsteps per 100 s²
  google.protobuf.UInt32Value current_limit = 5; //Determines the maximum motor coil current limit of the driver on the Tic
  google.protobuf.UInt32Value max_speed = 6; // microsteps per 10,000 s
  google.protobuf.UInt32Value starting_speed = 7; // microsteps per 10,000 s
  google.protobuf.UInt32Value custom_step_size = 8; // microsteps per user defined step (not the stepper motor step)
  messaging.StepMode step_mode = 9; // microsteps per stepper defined step
  google.protobuf.DoubleValue spool_radius = 10; // the initial radius of the spool, only populated if we're calculating the steps dynamically
  google.protobuf.DoubleValue filter_paper_thickness = 11; // thickness of the filter paper on the spool, only populated if we're calculating the steps dynamically
  google.protobuf.DoubleValue ideal_linear_step_size = 12; // the ideal size of our individual steps taken by the spool, only populated if we're calculating the steps dynamically
  google.protobuf.DoubleValue step_angle = 13;
  bool dynamic_step_calculation = 14; // determines whether we calculate the number of steps we take dynamically
  bool simulated = 15; // whether or not this stepper controller is simulated or not
}