<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
      <nullable>enable</nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;SIM</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ares.Core.Grpc" Version="2024.6.14.134325" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.61.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Certificate" Version="6.0.28" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.28" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="6.0.28" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.31">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.28" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ARESCore\ARESCore.csproj" />
    <ProjectReference Include="..\ARESMessaging\ARESMessaging.csproj" />
    <ProjectReference Include="..\LindbergFurnace\LindbergFurnace.csproj" />
    <ProjectReference Include="..\SyringePumpNE1000\SyringePumpNE1000.csproj" />
    <ProjectReference Include="..\TicStepperController\TicStepperController.csproj" />
    <ProjectReference Include="..\ValveController\ValveController.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ARESServiceCert.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
