<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ares.DataModel.Grpc" Version="2023.1.20.175633" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Radzen.Blazor" Version="4.3.7" />
    <PackageReference Include="ReactiveUI.Blazor" Version="18.3.1" />
    <PackageReference Include="ReactiveUI.Fody" Version="18.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TC0304\TC0304.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Views\Tc0304ControlWidgetView.razor.css">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>



</Project>
