<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.33.5" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Drawing.Common" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
		<None Remove="Proto\DataModel.proto" />
		<None Remove="Proto\Services.proto" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.Device.USB\Ares.Device.USB.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Protobuf Include="Proto\DataModel.proto" GrpcServices="None" ProtoRoot="Proto" />
		<Protobuf Include="Proto\Services.proto" ProtoRoot="Proto" />
		<Protobuf Include="Proto\FlirCM3Config.proto" GrpcServices="None" ProtoRoot="Proto" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="SpinnakerNET_v140">
	    <HintPath>ThirdParty\SpinnakerNET_v140.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Resources\" />
	</ItemGroup>

</Project>
